# Check there for the free amount we have https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions
# Check there for doc https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on

name: Test

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: false
      # Unit tests with bash
      - name: Bash unit tests
        shell: bash
        run: |
          wget -q https://raw.githubusercontent.com/tlevine/urchin/v0.0.6/urchin
          chmod +x ./urchin
          ./urchin -s bash ./test
