# Check there for the free amount we have https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions
# Check there for doc https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on

name: Test

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false
      # Install zsh on Linux
      - name: Install zsh on Linux
        if: runner.os == 'Linux'
        run: sudo apt install zsh
      # Install zsh on Mac
      - name: Install zsh on Mac
        if: runner.os == 'macOs'
        run: brew install zsh
      # Retrieve urchin
      - name: Retrieve urchin
        run: |
          wget -q https://raw.githubusercontent.com/tlevine/urchin/v0.0.6/urchin
          chmod +x ./urchin
      # Unit tests with bash
      - name: Bash unit tests
        run: |
          ./urchin -s bash ./test
      # Unit tests with bash
      - name: Zsh unit tests
        run: |
          ./urchin -s zsh ./test
      # Unit tests with dash
      - name: Dash unit tests
        run: |
          ./urchin -s dash ./test
